# Read about fixtures at http://ar.rubyonrails.org/classes/Fixtures.html

1:
  id: 1
  name: ui.title
  value: Drone Interface
  namespace: 
  description: The default title for any UI web page.
  default_value: Drone Interface
