# Read about fixtures at http://ar.rubyonrails.org/classes/Fixtures.html

1:
  id: 1
  name: ui.title
  value: Drone Interface
  namespace: 
  description: The default title for any UI web page.
  default_value: Drone Interface

2:
  id: 2
  name: amqp.address
  value: 172.16.164.10
  namespace: collector
  description: The hostname or IP address of the AMQP server to obtain updated events from the Honeyclients.
  default_value: 127.0.0.1

3:
  id: 3
  name: amqp.user_name
  value: honeyclient
  namespace: collector
  description: The user name used to authenticate to the AMQP server.
  default_value: honeyclient

4:
  id: 4
  name: amqp.password
  value: passw0rd
  namespace: collector
  description: The password used to authenticate to the AMQP server.
  default_value: passw0rd

5:
  id: 5
  name: amqp.virtual_host
  value: /honeyclient.org
  namespace: collector
  description: The virtual host used to authenticate to the AMQP server.
  default_value: /honeyclient.org

6:
  id: 6
  name: events_exchange_name
  value: events
  namespace: collector
  description: The name of the AMQP exchange used to send events to this component.
  default_value: events

7:
  id: 7
  name: queue_name
  value: drone
  namespace: collector
  description: The name of the AMQP queue used to send events to this component.
  default_value: drone

8:
  id: 8
  name: events_routing_key
  value: "#"
  namespace: collector
  description: The routing key used to bind the queue to the events exchange.
  default_value: "#"

9:
  id: 9
  name: commands_exchange_name
  value: commands
  namespace: collector
  description: The name of the AMQP exchange used to send commands to this component.
  default_value: commands

10:
  id: 10
  name: commands_routing_key
  value: drone.#
  namespace: collector
  description: The routing key used to bind the queue to the commands exchange.
  default_value: drone.# 
