test:
  ttl: 60480
  namespace: drone-test
  sessions: false
  debug: false
  servers: 172.16.164.2:11211

development:
  ttl: 60480
  namespace: drone-production
  sessions: false
  debug: false
  servers: 172.16.164.2:11211

production:
  ttl: 60480
  namespace: drone-production
  sessions: false
  debug: false
  servers: 172.16.164.2:11211
