
# The name of the generated spec file
output_file: "messages_spec.proto"

# The list of models you'd like to
# generate a spec for. Note: use the 
# 'filename' of the model NOT the class name.
models:
- application
- client
- client_status
- file_content
- fingerprint
- host
- job_alert
- job
- job_source
- os_process
- os
- process_file
- process_registry
- url
- url_status
