# Configuration file for workers.
# You can configure to run more than one worker with the same rake task.
# Each instance of a task should have a different (unique) pidfile name.
# For example to run two collector tasks with the same worker, you can setup
# the configuration like the example below. Note the pidfiles names are unique.
# You must also set the phonehome to the shortname address of the node running
# the worker console.

collector_high:
  pidfile: "tmp/pids/collector_high.pid"
  command: "collector:high:start_detached"
  phonehome: "theman_console@drone"

collector_low:
  pidfile: "tmp/pids/collector_low.pid"
  command: "collector:low:start_detached"
  phonehome: "theman_console@drone"

notifier:
  pidfile: "tmp/pids/notifier.pid"
  command: "notifier:start_detached"
  phonehome: "theman_console@drone"

