#!/bin/sh
cat config/initializers/session_store.rb | sed -e "s/:secret      => '.*/:secret      => '`rake secret | tail -n 1`'/" > config/initializers/session_store.rb
cat config/initializers/site_keys.rb | sed -e "s/REST_AUTH_SITE_KEY         = '.*/REST_AUTH_SITE_KEY         = '`rake secret | tail -n 1`'/" > config/initializers/site_keys.rb
